TrainEnv:
  sections:
  - target:
    - 13
    - -60.06
    - -10.37
    offset1:
    - -0.15
    offset2:
    - -27.5
    offset3:
    - -11
    offset4:
    - -1.05
    offset5:
    - -1.57

  - target:
    - 6.74
    - -97
    - -12.52
    offset1:
    - 13
    offset2:
    - -60.06
    offset3:
    - -10.37
    offset4:
    - -1.57
    offset5:
    - -1.92

  - target:
    - -12.8
    - -124.2
    - -22
    offset1:
    - 6.74
    offset2:
    - -97
    offset3:
    - -12.52
    offset4:
    - -1.92
    offset5:
    - 3.8

  - target:
    - -45.5
    - -137
    - -18
    offset1:
    - -12.8
    offset2:
    - -124.2
    offset3:
    - -22
    offset4:
    - 3.8
    offset5:
    - 3.05
  
  - target:
    - -84.3
    - -123.3
    - -12.3
    offset1:
    - -45.5
    offset2:
    - -137
    offset3:
    - -18
    offset4:
    - 3.05
    offset5:
    - 2.45

  - target:
    - -115.5
    - -91
    - -7
    offset1:
    - -84.3
    offset2:
    - -123.3
    offset3:
    - -12.3
    offset4:
    - 2.45
    offset5:
    - 1.95

  - target:
    - -113.3
    - -51.5
    - -14
    offset1:
    - -115.5
    offset2:
    - -91
    offset3:
    - -7
    offset4:
    - 1.95
    offset5:
    - 1.3

  - target:
    - -80.2
    - -17.5
    - -17.5
    offset1:
    - -113.3
    offset2:
    - -51.5
    offset3:
    - -14
    offset4:
    - 1.3
    offset5:
    - 0.7

  - target:
    - -76
    - -7.6
    - -11
    offset1:
    - -80.2
    offset2:
    - -17.5
    offset3:
    - -17.5
    offset4:
    - 0.7
    offset5:
    - 0.35

  - target:
    - -0.15
    - -27.5
    - -11
    offset1:
    - -41.1
    offset2:
    - -8
    offset3:
    - -16
    offset4:
    - -0.3
    offset5:
    - -1.05